TCP_SERVER:
  HOST: '192.168.0.8'
  PORT: 8080
  TCP_PORT: 8082
  CORS_ORIGINS: ['*']

FCM:
  API_KEY:

LOGGER:
  PATH: 'log'

# ABS   : 절대값
# REAL  : 실제값
STAT:
  VIB: ABS
  TEMP: REAL

DATABASE:
  PATH: 'db'
